/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "Timer1.h"
#include "isr_timer.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "WaveDAC8_1.h"
#include "Clock_2.h"
#include "Pin_Led_aliases.h"
#include "Pin_Led.h"
#include "Opamp_1.h"
#include "Vout_1_aliases.h"
#include "Vout_1.h"
#include "Clock_1.h"
#include "Clock_3.h"
#include "Clock_4.h"
#include "PWM_1.h"
#include "ADC_LongitudNota.h"
#include "Entrada_Potenciometro_aliases.h"
#include "Entrada_Potenciometro.h"
#include "UART_1.h"
#include "isr_rx.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "ADC_LongitudNota_IRQ.h"
#include "ADC_LongitudNota_theACLK.h"
#include "UART_1_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

